services:
  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"  
    depends_on:
      - backend
